/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Yahia Hamimi
 ******************************************************************************/


/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION           (1U)
#define PORT_PBCFG_SW_MINOR_VERSION           (0U)
#define PORT_PBCFG_SW_PATCH_VERSION           (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION   (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION   (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION   (3U)


#include "Port.h"


/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif


 const Port_ConfigType Port_Configuration = {
 TIVA_C_PORTA, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN3, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN4, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN5, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN6, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTA, TIVA_C_PORT_PIN7, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN3, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN4, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN5, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN6, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTB, TIVA_C_PORT_PIN7, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN3, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN4, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN5, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN6, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTC, TIVA_C_PORT_PIN7, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN3, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN4, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN5, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN6, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTD, TIVA_C_PORT_PIN7, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN3, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN4, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTE, TIVA_C_PORT_PIN5, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTF, TIVA_C_PORT_PIN0, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTF, TIVA_C_PORT_PIN1, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTF, TIVA_C_PORT_PIN2, PORT_PIN_IN, OFF, PORT_PIN_DIO_MODE, DIRECTION_NOT_CHANGEABLE, MODE_NOT_CHANGEABLE, STD_LOW,
 TIVA_C_PORTF, TIVA_C_PORT_PIN3, PORT_PIN_OUT, OFF, PORT_PIN_DIO_MODE, DIRECTION_CHANGEABLE, MODE_CHANGEABLE, STD_LOW,
 TIVA_C_PORTF, TIVA_C_PORT_PIN4, PORT_PIN_IN, PULL_UP, PORT_PIN_DIO_MODE, DIRECTION_CHANGEABLE, MODE_CHANGEABLE, STD_LOW,
 };






